### PR TITLE
Theme 0.1 trading data page upgrade

### PR DESCRIPTION
**Pull request by kenkunz**
## Design note

Alek will likely be making some design updates to this page this week based on feedback from Mikko. We agreed at 08.08 design sync to merge and deploy this version and then handle design changes iteratively (since it is an improvement over what we have live now).

## Notes for code review

A lot of files were updated – quick FAQ to help filter the signal from the noise:

**Why `svelte` upgrade?**
> so we can use newer `<svelte:element>` feature. This is very low risk (compared to SvelteKit upgrade). Tested across many pages / browsers / devices – no issues found.

**Why did all the SVGs change?**
> removed explicit `width` / `height` references – simplifies sizing and positioning for inlined SVGs. Tested thoroughly.

**What are the main changes needing review?**
> [ContentTile.svelte](src/lib/components/ContentTile.svelte) – updated to support horizontal layout / include a button when needed
> [trading-view/index.svelte](src/routes/trading-view/index.svelte) – updated with new theme header and above component for tiles

### CODE REVIEW

**Comment by kenkunz** [comment]
@hieuh25 or @allozaur (or whoever has time to review) – a lot of files were updated – quick FAQ to help filter the signal from the noise:

**Why `svelte` upgrade?**
> so we can use newer `<svelte:element>` feature. This is very low risk (compared to SvelteKit upgrade). Tested many pages on various browsers / devices – no issues found.

**Why did all the SVGs change?**
> removed explicit `width` / `height` references – simplifies sizing and positioning for inlined SVGs. Tested thoroughly.

**What are the main changes needing review?**
> [ContentTile.svelte](src/lib/components/ContentTile.svelte) – updated to support horizontal layout / include a button when needed
> [trading-view/index.svelte](src/routes/trading-view/index.svelte) – updated with new theme header and above component for tiles

**Comment by kenkunz** [comment]
Converting this to "draft" until some design questions are finalized (based on feedback from Mikko).

**Comment by kenkunz** [comment]
closes #162

**Review by servatj — APPROVED** [review]
LGTM :)

**Pull request merged**
