### PR TITLE
Handles 422 error when no token data tracked

### PR DESCRIPTION
**Pull request by servatj**
Handles 422 error message and set a default message when the response is not ok. 

image

### CODE REVIEW

**Comment by servatj** [comment]
Or we can show this @miohtama 

image

What you prefer ?

**Comment by kenkunz** [comment]
@servatj I started reviewing this … but it's taking me some time to grok the `Datatables` approach. I'll take another look in the morning.

My initial feedback is I think the `ajax()` method is too long to follow – I think we could extract a few chunks of this into separate methods to make it easier to understand. I'll add some more specific thoughts tomorrow.

**Comment by servatj** [comment]
Yeah, @kenkunz  I think we have to discuss what will be the approach on the architecture of the frontend from now, we can talk on and after daily. I'm happy to pair with you or if you want to lead this refactor I'm happy to follow too.

**Comment by kenkunz** [comment]
@servatj here's what I envision for a "light touch" refactor to trim down the `ajax()` function:
* extract all of the code related to URL request params into a new function (`getParams()` or something similar)
  * find a better pattern for all of the `if(localVar) { ... }` blocks (I have a couple ideas)
* extract the custom error handling code into a new function (`getErrorResponse()` or something similar)
* DRY-up some other duplication / minor cleanup

When we're done, `ajax()` (pseudocode) should look something like:
```
ajax()
    getParams()
    fetch(url with params)
    let result

    if (resp.ok)
        set result
    else
        getErrorResponse()
        set Datatables settings and result

    callback(result)
```

… which I think will be much easier to read / follow.

If you'd like to pair on this, I'm available tomorrow (Friday) between 9-11a CDT / 3-5p CET or after the Daily.

Thoughts?

**Comment by kenkunz** [comment]
@miohtama Josep and I paired on this today and cleaned up the `ajax()` method. Good-to-merge from our perspective!

**Review by kenkunz — APPROVED** [review]
pair-programming FTW!

**Comment by miohtama** [comment]
The purpose of this issue was to have a good server-side error messages, which can be passed through, so we do not need to have any client-side messages.

If I understand correctly, this pull request actually adds more client-side messages?

image

**Comment by servatj** [comment]
> The purpose of this issue was to have a good server-side error messages, which can be passed through, so we do not need to have any client-side messages.
> 
> If I understand correctly, this pull request actually adds more client-side messages?
> 
> image

Ok is see we will always return the error from the API we won't need the manage error codes at all on the frontend!

**Pull request merged**
