### PR TITLE
feat: Wallet Widget UI/UX + Strategy Tile refactor

### PR DESCRIPTION
**Pull request by allozaur**
Close tradingstrategy-ai/design-system#125

https://github.com/tradingstrategy-ai/frontend/assets/37627284/37b1e7cc-8825-40d5-936b-42139556600a

### CODE REVIEW

**Comment by allozaur** [comment]
https://github.com/tradingstrategy-ai/frontend/assets/37627284/95f5eb6c-c85e-446b-800c-aa079e81d19f

@miohtama i addressed all of your remarks.

- changed circle ball (jazzicon) to wallet icon. I have a feeling that users might ask for this feature in future, so we will see ;)
- As it goes for the `Connect wallet` button when there is already a wallet connection — we discussed earlier that we wanted to have `Change wallet` there, so i put this label over there. For now these are only dummy UI elements, so changing it to `Cancel wallet` is no-effort change, which i will leave to @kenkunz when he connects this with business logic.

Also with this design we have some space left on the middle-left, between the CTAs and the Wallet Widget. I think that we can leave this for now as it is, but in the future we can improve this layout in general so the elements might eventually be rearranged.

Tell me your thoughts!

**Comment by allozaur** [comment]
https://github.com/tradingstrategy-ai/frontend/assets/37627284/23f7f23f-53e0-4a83-bfb6-8dfa40505359

**Comment by miohtama** [comment]
Let's ship it 👍

**Comment by allozaur** [comment]
> Let's ship it 👍

@kenkunz passing this one to u ;)

**Comment by kenkunz** [comment]
@allozaur, @miohtama –

### My 2¢ on the most recent design changes…

#### Vertical real-estate

The investor widget now takes up a huge amount of screen real estate on the Strategy overview page (a full **66% taller** than original on desktop / **54% taller** on mobile). Here's what it looks like on a `1366x768` screen (still the 2nd most common desktop resolution):

localhost_5173_strategies_enzyme-polygon-eth-usdc

#### Other sub-optimal aspects of new layout

There are several other aspects of this layout that I find to be visually distracting or sub-optimal compared to the original design:
1. three color layers (vs 2 in original design) – makes my brain work a little harder to absorb the information
2. slight mis-alignment between the data boxes / layers and the buttons below
3. the "your wallet is connected" alert doesn't seem to add anything but draws a lot of visual attention
4. insufficient space for the balance values when values are longer or screen width is smaller (causing wrapping)

investor widget v2

#### Side-by-side comparison

Here are the two designs side-by-side for comparison. To me, the one on the right is both more visually appealing and requires less effort for me to interpret the information.

<table>
<tr>
<td valign="top">
investor widget v2
</td>
<td valign="top">
investor widget v2
</td>
</tr>
</table>

**Comment by miohtama** [comment]
Alert can go away. It is not needed.

**Comment by allozaur** [comment]
@kenkunz in terms of information density i definitely agree that we need to improve that, so for now we can try to figure out some quick win with what we have currently, but also i think that we will address this issue in upcoming typography/layout improvements that will be worked on after we deliver the Strategies x Wallet MVP

**Comment by allozaur** [comment]
Zrzut ekranu 2023-05-16 o 14 52 48

@miohtama @kenkunz i think this one will work

**Comment by kenkunz** [comment]
@allozaur lgtm!

**Comment by allozaur** [comment]
@miohtama here are the recordings for Redeem wizard:

https://github.com/tradingstrategy-ai/frontend/assets/37627284/4dbb0254-5285-4f25-88c7-bf60c9cf5278


https://github.com/tradingstrategy-ai/frontend/assets/37627284/b4303eef-b8bb-467a-9862-bb4f44a80f70

**Comment by kenkunz** [comment]
@allozaur I encountered a few issues with the `StrategyTile` refactor so I did not merge those changes.

If you'd like to tackle these, let's move the work off to a separate branch/PR to keep it isolated. I am open to addressing these as well, but in that case let's move it to a separate GH issue that is lower priority (`P3`), since we have a lot of other features in queue that are higher priority.

### 1. Visual layout issues at various viewport widths

<table>
<thead>
<tr>
<th width="33.3%">
  <code>viewport &gt;= 1360px</code>
</th>
<th width="33.3%">
  <code>1196px &gt= viewport &gt= 968px</code>
</th>
<th width="33.3%">
  <code>967px &gt= viewport &gt= 688px</code>
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
  Inconsistent tile height due to differences in tile content wrapping / height.
</td>
<td>
  Inconsistent tile height due to differences in tile content wrapping / height.
</td>
<td>
  Chart fails to stretch to full tile height
</td>
</tr>
<tr>
<td>
image
</td>
<td>
image
</td>
<td>
image
</td>
</tr>
</tbody>
<table>

### 2. `:global` CSS overrides

The updated `StrategyTile` component overrides a whole bunch of `ContentCard` CSS. I have been trying to avoid / eliminate the use of this pattern. This approach breaks encapsulation, making it impossible to change the implementation  of `ContentCard` without a high risk of breaking `StrategyTile` (or other parents that apply overrides). This results in UI bugs and and makes it harder to modify existing components.

Whenever possible, if a parent component needs to configure some visual/layout aspect of a child, this should be exposed as a `prop` or a custom CSS property, or the child should "yield control" to the parent via a `slot`. There are very rare cases where a `:global` override makes sense, but this should be the exception not the rule.

**Comment by kenkunz** [comment]
@allozaur since this PR has a lot of different changes and has diverged significantly from `master`, I pulled the redeem wizard changes over to a separate branch/PR – see #451.

If it looks like I captured everything, let's close this PR.

**Comment by miohtama** [comment]
@allozaur On a mobile wallet / WalletConnect, there is not going to be a pop-up, so we need to change the message.

"Confirm the transaction in your wallet app."

Also @kenkunz can confirm if we can display the app name if this information is available.

**Comment by allozaur** [comment]
> @allozaur I encountered a few issues with the `StrategyTile` refactor so I did not merge those changes.
> 
> 
> 
> If you'd like to tackle these, let's move the work off to a separate branch/PR to keep it isolated. I am open to addressing these as well, but in that case let's move it to a separate GH issue that is lower priority (`P3`), since we have a lot of other features in queue that are higher priority.
> 
> 
> 
> ### 1. Visual layout issues at various viewport widths
> 
> 
> 
> <table>
> 
> <thead>
> 
> <tr>
> 
> <th width="33.3%">
> 
>   <code>viewport &gt;= 1360px</code>
> 
> </th>
> 
> <th width="33.3%">
> 
>   <code>1196px &gt= viewport &gt= 968px</code>
> 
> </th>
> 
> <th width="33.3%">
> 
>   <code>967px &gt= viewport &gt= 688px</code>
> 
> </th>
> 
> </tr>
> 
> </thead>
> 
> <tbody>
> 
> <tr>
> 
> <td>
> 
>   Inconsistent tile height due to differences in tile content wrapping / height.
> 
> </td>
> 
> <td>
> 
>   Inconsistent tile height due to differences in tile content wrapping / height.
> 
> </td>
> 
> <td>
> 
>   Chart fails to stretch to full tile height
> 
> </td>
> 
> </tr>
> 
> <tr>
> 
> <td>
> 
> image
> 
> </td>
> 
> <td>
> 
> image
> 
> </td>
> 
> <td>
> 
> image
> 
> </td>
> 
> </tr>
> 
> </tbody>
> 
> <table>
> 
> 
> 
> ### 2. `:global` CSS overrides
> 
> 
> 
> The updated `StrategyTile` component overrides a whole bunch of `ContentCard` CSS. I have been trying to avoid / eliminate the use of this pattern. This approach breaks encapsulation, making it impossible to change the implementation  of `ContentCard` without a high risk of breaking `StrategyTile` (or other parents that apply overrides). This results in UI bugs and and makes it harder to modify existing components.
> 
> 
> 
> Whenever possible, if a parent component needs to configure some visual/layout aspect of a child, this should be exposed as a `prop` or a custom CSS property, or the child should "yield control" to the parent via a `slot`. There are very rare cases where a `:global` override makes sense, but this should be the exception not the rule.
> 
> 

@kenkunz Sure i will address it in a separate PR

**Comment by kenkunz** [comment]
This PR has largely been superseded and addressed by #448 and #451. Small remaining items pulled out to separate issues #488 and #490.

**Pull request closed without merging**
