### PR TITLE
deposit wizard UX enhancements

### LINKED ISSUE #455: Deposit wizard UX enhancements
# Goal

Improve deposit wizard UX

## Details

- on `balance` page, include CTAs to purchase native currency (e.g., MATIC) and/or USDC
- on `success` page, show share quantity and USDC value
- on `purchase` page, improve error recovery – allow the user to try again if they reject the signing or transaction wallet requests

### PR DESCRIPTION
**Pull request by kenkunz**
closes #455

### CODE REVIEW

**Comment by kenkunz** [comment]
## Low token balance notice / CTA

<table>
<thead>
<tr>
<th>Desktop</th>
<th>Mobile</th>
</tr>
</thead>
<tbody>
<tr>
<td width="68%">
image
</td>
<td width="32%">
image
</td>
</tr>
</tbody>
</table>

**Comment by kenkunz** [comment]
## Success screen with share balance / value

<table>
<thead>
<tr>
<th>Desktop</th>
<th>Mobile</th>
</tr>
</thead>
<tbody>
<tr>
<td width="68%">
image
</td>
<td width="32%">
image
</td>
</tr>
</tbody>
</table>

**Comment by allozaur** [comment]
@kenkunz it looks great :)

**Review by allozaur — APPROVED** [review]
@kenkunz it looks great :) good work!

**Pull request merged**
