### PR TITLE
New Strategy Tile UI

### LINKED ISSUE #488: Strategy index tile enhancements
# Goal

Improve appearance and usability of strategy index tiles.

## Details

- [x] entire tile should be clickable (vs. just "View strategy" button)
- [x] ensure the tile layout looks correct across viewport widths
- [x] add strategy icon as shown in pitch deck mock up below

> **Note** adding a "mountain" gradient to chart (similar to Performance tab) is out of scope of this ticket – see #489)

## Mock up from pitch deck

image

### LINKED ISSUE #546: Improve UI/UX of Tooltip component
# Goal

A `<Tooltip>` component was recently introduced in order to provide quick access to info about metrics, labels, etc. While functional, the component would benefit greatly from some UI and UX refinements.

## Details

- improve visual style of Tooltip popup (more consistent with our visual theme)
- improve trigger / display UX (e.g., delay and duration of popup display on-hover)
- improve popup positioning and sizing
   - tooltip should position in appropriate location relative to location of trigger and available screen real estate
   - tooltip should be sized appropriately
- improve tooltip affordance (e.g. use a `( ? )` icon or `*` instead of dotted-underline)
- ensure tooltip is accessible
- ensure Tooltip component works in all required contexts (grep for current usage; test in Datatable header and content cells)

## Implementation considerations

We shouldn't reinvent the wheel here. There are likely some good Svelte headless component / action libraries that provide a lot of the core functionality and allow us to apply our own CSS styles.

### PR DESCRIPTION
**Pull request by allozaur**
Close #488
Close #546

### Desktop

https://github.com/tradingstrategy-ai/frontend/assets/37627284/24abd4c3-8f62-466f-94c4-0acd83a41c2f

### Mobile

https://github.com/tradingstrategy-ai/frontend/assets/37627284/f0ccafca-696b-4bba-9cbd-5f748ff82ce7

### CODE REVIEW

**Comment by kenkunz** [comment]
@allozaur I believe you said at design sync that you still had 1 or 2 commits to add (e.g., putting the SVG chart back in). I also see that the `format` and `test` checks are failing.

I'll move this to `draft` state for now – lmk when it's ready for review.

_Thanks!_

**Comment by allozaur** [comment]
https://github.com/tradingstrategy-ai/frontend/assets/37627284/b81fbdd1-ecad-4d53-a50b-ed6e6faff658

**Review by kenkunz — CHANGES_REQUESTED** [review]
Per discord discussion, the following items should be addressed before this is ready to be merged:

- [x] Fix unscoped global CSS `@import` issue (leaked style bugs site-wide)
- [x] Replace JS-based tile→button hover/focus code with CSS-only pattern we've used elsewhere
   - JS approach is more complex, somewwhat buggy, and has accessibility issues
- [x] Remove `ButtonNew` component
   - Let's avoid having rudundant/parallel components – they can easily become a form of _long-lived, "short-term" tech-debt_. If changes are needed to `Button` let's address them site-wide or at least have a clear migration plan first.
- [x] Bring back missing error messages. Perhaps an error icon with tooltip instead of embedded alert? (needs @miohtama's feedback)
- [ ] Add strategy icons (using `strategy.icon_url` property?)
   - this property does not appear to have valid values on most (or all?) strategies; still seems worthwhile to implement with assumption that the `icon_url` prop can be quickly corrected on each strategy.
- [x] Fix broken tests
- [ ] Fix "page jank" (see comment below)

I still have additional code to review and can continue with that on Monday.

**Comment by kenkunz** [comment]
> * [ ] Add strategy icons (using `strategy.icon_url` property?)

@allozaur as I am working on adding some better test fixture data, I realized that this is already implemented 😄. The only reason I was not seeing strategy icons in Prod is that the strategies don't include a valid `icon_url`. I marked this one as done ☑️.

**Comment by kenkunz** [comment]
@allozaur I updated the strategy test fixture data to show three strategies on `/strategies` page: one fully working strategy, one with execution errors, one offline.

To use this in development:

```bash
npm run dev -- --mode=dev
```

Make sure you're not running any other `dev` instance so this starts on port `5173`. You should now be able to open the `/strategies` page locally at http://localhost:5173/strategies to see the three strategies.

If you want to see how the strategies _currently_ look (based on current `StrategyTile` that includes error alerts), kill the `dev` server and run the following:

```bash
git switch master
git restore --source=#488 -- .env.dev tests
npm run dev -- --mode=dev
```

To switch back to your branch in a clean state:

```bash
git restore .
git clean -f tests
git switch '#488'
```

**Comment by kenkunz** [comment]
@allozaur one more thing to add to the list…

I'm seeing some noticeable "page jank" when loading the `/strategies` page directly (vs. client-side nav). I don't see this behavior on `master` / in prod. I tested this against a `build` using `npm preview` to make sure it wasn't just a `dev` / HMR-related issue.

https://github.com/tradingstrategy-ai/frontend/assets/35901/66fbb149-a4cc-40cb-93ba-e7fe36d5f3bf

**Comment by allozaur** [comment]
@kenkunz regarding the "Fix "page jank", it seems that this is somehow caused by slotted components, e. g. Tooltip. I tested it and it seems that regardless of the way slots are used it happens either way... So not sure if it's sth related to Svelte version or anything else. I think that at this stage it's not severe enough to block us from introducing the changes.

**Comment by allozaur** [comment]
### Alert the old way

Zrzut ekranu 2023-08-22 o 14 34 52

### Alert as a small box with tooltip


https://github.com/tradingstrategy-ai/frontend/assets/37627284/875de989-71d3-41c7-98b6-9cb8a67f8ecb

**Review by kenkunz — APPROVED** [review]
I think this is finally good to merge 😌🤞

**Pull request merged**
