### PR TITLE
strategy deposit wizard

### LINKED ISSUE #426: Wallet integration – deposit tokens to strategy vault
# Goal

An **investor** should be able to deposit tokens to a particular strategy vault from the **deposit wizard payment** step.

### PR DESCRIPTION
**Pull request by kenkunz**
closes #426

This is a pretty large PR due to some reconfiguring of the wizard store code and some other refactoring. The core business logic associated with the actual **strategy deposit** is in these two files:
- [eth-defi/eip-3009.ts](https://github.com/tradingstrategy-ai/frontend/blob/426-deposit-wizard/src/lib/eth-defi/eip-3009.ts) – approval / signature of the USDC transfer
- [WalletDeposit.svelte](https://github.com/tradingstrategy-ai/frontend/blob/426-deposit-wizard/src/lib/wallet/WalletDeposit.svelte) – "payment" step of the deposit wizard – this is somewhat complex and involves a number of intermediate UI states, so this is managed with a finite state machine.

There are still a few UI elements to add in other steps of the deposit wizard, and some additional UX refinements that can be made, but this should be a good `v1`. Additional elements to complete include:
- UI for purchasing tokens when user doesn't have required token balances (on `balance` step)
- UI for displaying purchased shares (on `success` step)
- better error recovery – e.g., allowing the user to try again if they reject the auth or payment step in their wallet
- other minor UX refinements (e.g., a max constraint on the USDC investment amount based on current balance)

### CODE REVIEW

**Comment by kenkunz** [comment]
https://github.com/tradingstrategy-ai/frontend/assets/35901/1cd52faa-b357-416c-94df-4ffd0e2b16fa

**Review by miohtama — COMMENTED** [review]
is ABI included twice?

- src/lib/abi/enzyme
- src/lib/eth-defi/abi

**Comment by hieuh25** [comment]
> is ABI included twice?
> 
> * src/lib/abi/enzyme
> * src/lib/eth-defi/abi

Looks like the `src/lib/abi/enzyme` folder is deleted in this PR, so all good there

**Review by hieuh25 — APPROVED** [review]
LGTM

**Comment by kenkunz** [comment]
thanks, @hieuh25!

**Pull request merged**
