### PR TITLE
apply prettier format rules

### LINKED ISSUE #68: Standardize code formatting
## Goals
* standardize the code style conventions used in `frontend`
* keep it consistent with other Trading Strategy Svelte projects (e.g., `trade-executor-frontend`, `design-system`
* follow conventions that are standard in the Svelte / SvelteKit community (easier to introduce new developers with Svelte experience)
* automate it some developers don't need to think about it

### PR DESCRIPTION
**Pull request by kenkunz**
## Goals
* standardize the code style conventions used in `frontend`
* keep it consistent with other Trading Strategy Svelte projects (e.g., `trade-executor-frontend`, `design-system`
* follow conventions that are standard in the Svelte / SvelteKit community (easier to introduce new developers with Svelte experience)
* automate it so developers don't need to think about it

fixes #68

### CODE REVIEW

**Comment by kenkunz** [comment]
Our other Svelte projects are all using `prettier` with the standard `.prettierrc` configuration that ships with SvelteKit:
```json
{
	"useTabs": true,
	"singleQuote": true,
	"trailingComma": "none",
	"printWidth": 100
}
```

I have to admit… `tabs` was an adjustment for me, but I've grown to like it. Also this:

<a target="_blank" href="https://youtu.be/SsoOG6ZeyUI">
image
<div><b>Tabs versus Spaces</b></div>
</a>

**Comment by kenkunz** [comment]
## Usage

## VSCode

Install the standard Prettier extension and make sure it's enabled. Formats are auto-applied on file save.

## Other editors / IDEs

See editor support section [here](https://prettier.io/).

## command line

Run `npm run format` to reformat files.  Our CI runs `npm run format:check` to verify formats.

**Review by servatj — APPROVED** [review]
I prefer spaces, but is fine to use tabs :)

**Comment by kenkunz** [comment]
@miohtama per our discussion at Daily, I pushed an update with `"printWidth": 120` (and updated all source files accordingly) as well as documentation.

Should be good-to-merge!

**Pull request merged**
