### PR TITLE
feat: Create Closed Positions page

### PR DESCRIPTION
**Pull request by allozaur**
Close tradingstrategy-ai/design-system/issues/101

https://user-images.githubusercontent.com/37627284/208108820-f0ad9797-e789-4749-8b27-82c55cb45859.mov

### CODE REVIEW

**Comment by kenkunz** [comment]
Looking good!

I will do some work to unify the routing for `open-positions` and `closed-positions` in order to reduce duplication. E.g., we can create a route like `[status=positionStatus]-positions` and add a param validator to `/src/params`.

**Comment by kenkunz** [comment]
@allozaur – three additional UI elements that still need to be addressed are: **search**, **sort control / indicator**, and **pagination**.

These are not needed on `open-positions` because the number of open positions will always be small. The number of close positions can grow arbitrarily large. See the old `strategy/closed-positions` page for reference.

**Comment by allozaur** [comment]
> @allozaur – three additional UI elements that still need to be addressed are: **search**, **sort control / indicator**, and **pagination**.
> 
> These are not needed on `open-positions` because the number of open positions will always be small. The number of close positions can grow arbitrarily large. See the old `strategy/closed-positions` page for reference.

Alright i will handle these :)

**Comment by allozaur** [comment]
@kenkunz all of the UI ascpects are ready, i believe. I am handing the rest of this task over to you. What's left is:

- [ ] Connect pagination to real data
- [ ] Make the pagination work (optimally we could hande this using `<a>` tag and holding the pagination data in URL Search Params)
- [ ] Troubleshoot if we can make the `svelte-headless-table`'s filtering better — now it seems to be very picky

**Comment by allozaur** [comment]
@kenkunz i also noticed we lost the `<thead>`'s _stickyness_... i can try to retrieve this one. It also makes me think that maybe some simple e2e tests in Playwright could prevent this and other bugs with the Data Tables in the future?

I thought that i could write tests for these stories:

1. Scroll down and see if `<thead>` is visible.
2. Use Search Filter and check if the the rows with matching data can be located in DOM
3. Use Sort By and see if the first value is an expected one

@miohtama, @kenkunz lemme know what u think about this :)

**Comment by miohtama** [comment]
Stickyness is not necessary for the basic user experience.

Please focus on the basic user experience first, we can polish later.

**Comment by kenkunz** [comment]
this PR is superseded by #294

**Pull request closed without merging**
