### PR TITLE
Containerize frontend

### PR DESCRIPTION
**Pull request by servatj**
Fix https://github.com/tradingstrategy-ai/scratchpad/issues/6

### CODE REVIEW

**Review by hieuh25 — APPROVED** [review]
## Description
The `build` job basically build a new docker image of the target commit, then push it to Github Container Registry with relevant tag.
A new job named `build` is added to existing workflow `Automated test suite` so we can chain the jobs together: `build` job only runs if `test` job succeeds. At the time of writing, Github still doesn't support chaining workflows together natively. 

## How to trigger new build
`build` job will be triggered automatically when `test` passes in 1 of these scenarios:
* A new pull request is created, so we will have separate docker image per PR, which is very nice for testing purpose (locally or on staging)
* A new tag is created, this is a more proper way to handle release

## How to deploy
* Create a new PAT at https://github.com/settings/tokens with only 1 scope `read:packages` for security reason
* On the target host machine, login to Github container registry (`username` = your personal username, `password` = above PAT): `docker login ghcr.io`
* Choose an image from: https://github.com/tradingstrategy-ai/frontend/pkgs/container/frontend/versions
* Pull the image you chose: `docker pull ghcr.io/tradingstrategy-ai/frontend:<VERSION>`
* Prepare an [env file](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file) with needed environment variables
* Run new container with it: `docker run -dp 3000:TARGET_PORT --env-file MYENVFILE ghcr.io/tradingstrategy-ai/frontend:<VERSION>` 

## Possible next steps
* Clean up `package.json`,  there are some TODOs and missing info there, preferably together with #59 
* Have a proper release process, we can use https://docs.npmjs.com/cli/v8/commands/npm-version and document it somewhere
* Handle deployment with a proper orchestration tool like [Kubernetes](https://kubernetes.io/) or [Nomad](https://www.nomadproject.io/)

**Comment by kenkunz** [comment]
> * Run new container with it: `docker run -dp 3000:TARGET_PORT --env-file MYENVFILE ghcr.io/tradingstrategy-ai/frontend:<VERSION>`

the port numbers are reversed here – should be `TARGET_PORT:3000`

also, on mac M1, this additional flag is required: `--platform linux/amd64` – otherwise you get the following error:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

**Review by kenkunz — APPROVED** [review]
Looks good!

Fixed one small issue with `github.ref` check – full ref is `refs/heads/master` (vs. `master`), and simplified the expression (removed grouping) to make it a bit more readable.

Tweaked the `.yaml` formatting (inlined simple one-element arrays).

**Comment by kenkunz** [comment]
@hieuh25 this is ready for your review.

#### Switch from `alpine` to Debian / `slim`

I switched away from the `alpine` image to the default Debian image (using the `slim` version in the 2nd stage of the Dockerfile). The resulting image is only marginally larger than with the `alpine` image, and several of the build steps run faster. Also, using `alpine` requires manual installation of 5-6 packages that are included by default in the standard Debian image. With the benefits of multi-stage builds and and the `slim` version in final stage, I don't see much benefit to using `alpine` anymore.

#### Open question – `hooks/index.ts` local host reference

One item that still needs some discussion – when `VITE_SITE_MODE` is set to `production`, the `externalFetch` function in `hooks/index.ts` assumes that `http://127.0.0.1:3456` is where the `backend` API is being run.

This is not a valid assumption if we are running Docker networking in `bridge` mode (the default). I can think of a couple possible ways to address this. In the short-term (before we have moved all services to Docker), we can consider running in `host` network mode, which should allow the existing code to work as-is. Or if we want to stick with `bridge` mode, we can change the `hooks` code to reference the host machine using the special hostname of `host.docker.internal`. This would not work with our current deployment method, so we may need to make this local address configurable.

**Review by hieuh25 — APPROVED** [review]
LGTM

**Pull request merged**
